services:
  - type: web
    name: tickrify-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    branch: main
    environmentGroup: tickrify-env
    env:
      - key: ENVIRONMENT
        value: production
      - key: STRIPE_SECRET_KEY
        fromGroup: tickrify-env
        key: STRIPE_SECRET_KEY
    healthCheckPath: /health
    preDeployCommand: pip install -r backend/requirements.txt
